// Code generated by goctl. DO NOT EDIT.
// Source: serve.proto

package main

import (
	"context"

	"github.com/HuXin0817/bitkv/interval/pb"
)

type ServeServer struct {
	svcCtx *ServiceContext
	pb.UnimplementedServeServer
}

func NewServeServer(svcCtx *ServiceContext) *ServeServer {
	return &ServeServer{
		svcCtx: svcCtx,
	}
}

func (s *ServeServer) Put(ctx context.Context, in *pb.Pair) (*pb.Nil, error) {
	l := NewPutLogic(ctx, s.svcCtx)
	return l.Put(in)
}

func (s *ServeServer) Get(ctx context.Context, in *pb.Key) (*pb.Value, error) {
	l := NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
