// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: serve.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Serve_Put_FullMethodName = "/serve.Serve/Put"
	Serve_Get_FullMethodName = "/serve.Serve/Get"
)

// ServeClient is the client API for Serve service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServeClient interface {
	Put(ctx context.Context, in *Pair, opts ...grpc.CallOption) (*Nil, error)
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
}

type serveClient struct {
	cc grpc.ClientConnInterface
}

func NewServeClient(cc grpc.ClientConnInterface) ServeClient {
	return &serveClient{cc}
}

func (c *serveClient) Put(ctx context.Context, in *Pair, opts ...grpc.CallOption) (*Nil, error) {
	out := new(Nil)
	err := c.cc.Invoke(ctx, Serve_Put_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serveClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, Serve_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServeServer is the server API for Serve service.
// All implementations must embed UnimplementedServeServer
// for forward compatibility
type ServeServer interface {
	Put(context.Context, *Pair) (*Nil, error)
	Get(context.Context, *Key) (*Value, error)
	mustEmbedUnimplementedServeServer()
}

// UnimplementedServeServer must be embedded to have forward compatible implementations.
type UnimplementedServeServer struct {
}

func (UnimplementedServeServer) Put(context.Context, *Pair) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedServeServer) Get(context.Context, *Key) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServeServer) mustEmbedUnimplementedServeServer() {}

// UnsafeServeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServeServer will
// result in compilation errors.
type UnsafeServeServer interface {
	mustEmbedUnimplementedServeServer()
}

func RegisterServeServer(s grpc.ServiceRegistrar, srv ServeServer) {
	s.RegisterService(&Serve_ServiceDesc, srv)
}

func _Serve_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Serve_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeServer).Put(ctx, req.(*Pair))
	}
	return interceptor(ctx, in, info, handler)
}

func _Serve_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Serve_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServeServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

// Serve_ServiceDesc is the grpc.ServiceDesc for Serve service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Serve_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serve.Serve",
	HandlerType: (*ServeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Serve_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Serve_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serve.proto",
}
